controller_manager:
  ros__parameters:
    update_rate: 30
    # use_sim_time: true

    diff_cont:
      type: diff_drive_controller/DiffDriveController  # Using the SkidSteerController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_cont:
  ros__parameters:

    publish_rate: 50.0

    base_frame_id: base_link

    # Define the left and right wheel joints (both front and rear)
    left_wheel_names: ['left_front_wheel_joint', 'left_rear_wheel_joint']
    right_wheel_names: ['right_front_wheel_joint', 'right_rear_wheel_joint']

    # Set the physical parameters
    wheel_separation: 0.35  # Distance between left and right wheel sets
    wheel_radius: 0.05      # Radius of the wheels

    use_stamped_vel: false

    # Optional parameters
    # odom_frame_id: odom
    # enable_odom_tf: true

    # Limits (uncomment and configure these if you need limits)
    # linear.x.has_velocity_limits: true
    # linear.x.max_velocity: 1.0
    # angular.z.has_velocity_limits: true
    # angular.z.max_velocity: 1.0

    # Safety configurations (timeouts, etc.)
    # cmd_vel_timeout: 0.5
    # publish_limited_velocity: true
    # velocity_rolling_window_size: 10

joint_broad:
  ros__parameters:
    publish_rate: 50.0


    # open_loop: false    

    # wheels_per_side: x
    # wheel_separation_multiplier: x
    # left_wheel_radius_multiplier: x
    # right_wheel_radius_multiplier: x

    # odom_frame_id: x
    # pose_covariance_diagonal: x
    # twist_covariance_diagonal: x
    # open_loop: x
    # enable_odom_tf: x

    # cmd_vel_timeout: x
    # publish_limited_velocity: x
    # velocity_rolling_window_size: x
    

    # linear.x.has_velocity_limits: false
    # linear.x.has_acceleration_limits: false
    # linear.x.has_jerk_limits: false
    # linear.x.max_velocity: NAN
    # linear.x.min_velocity: NAN
    # linear.x.max_acceleration: NAN
    # linear.x.min_acceleration: NAN
    # linear.x.max_jerk: NAN
    # linear.x.min_jerk: NAN

    # angular.z.has_velocity_limits: false
    # angular.z.has_acceleration_limits: false
    # angular.z.has_jerk_limits: false
    # angular.z.max_velocity: NAN
    # angular.z.min_velocity: NAN
    # angular.z.max_acceleration: NAN
    # angular.z.min_acceleration: NAN
    # angular.z.max_jerk: NAN
    # angular.z.min_jerk: NAN




# joint_broad:
#   ros__parameters:
